# Generated by Django 5.2 on 2025-11-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datacenter", "0004_merge_20251128_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="looking_for",
            field=models.CharField(
                blank=True,
                help_text="Например: 'Ищу Python-разработчика' или 'Ищу инвестора'",
                max_length=255,
                verbose_name="Кого ищет",
            ),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма (руб)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datacenter.participant",
                        verbose_name="Кто задонатил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Донат",
                "verbose_name_plural": "Донаты",
            },
        ),
    ]
